using System;
using System.Collections.Generic;

namespace TCG_COMPANION.Utils
{
	public class PokemonSetHolder
	{
		public Dictionary<string, string> SetNameToId { get; private set; }

		public PokemonSetHolder()
		{
			SetNameToId = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
			{
					{"Base Set", "base1" },
					{ "Jungle", "base2" },
					{ "Wizards Black Star Promos", "basep" },
					{ "Fossil", "base3" },
					{ "Base Set 2", "base4" },
					{ "Team Rocket", "base5" },
					{ "Gym Heroes", "gym1" },
					{ "Gym Challenge", "gym2" },
					{ "Neo Genesis", "neo1" },
					{ "Neo Discovery", "neo2" },
					{ "Southern Islands", "si1" },
					{ "Neo Revelation", "neo3" },
					{ "Neo Destiny", "neo4" },
					{ "Legendary Collection", "base6" },
					{ "Expedition Base Set", "ecard1" },
					{ "Aquapolis", "ecard2" },
					{ "Skyridge", "ecard3" },
					{ "Ruby & Sapphire", "ex1" },
					{ "Sandstorm", "ex2" },
					{ "Dragon", "ex3" },
					{ "Nintendo Black Star Promos", "np" },
					{ "Team Magma vs Team Aqua", "ex4" },
					{ "Hidden Legends", "ex5" },
					{ "FireRed & LeafGreen", "ex6" },
					{ "POP Series 1", "pop1" },
					{ "Team Rocket Returns", "ex7" },
					{ "Deoxys", "ex8" },
					{ "Emerald", "ex9" },
					{ "Unseen Forces", "ex10" },
					{ "POP Series 2", "pop2" },
					{ "Delta Species", "ex11" },
					{ "Legend Maker", "ex12" },
					{ "POP Series 3", "pop3" },
					{ "Holon Phantoms", "ex13" },
					{ "Crystal Guardians", "ex14" },
					{ "POP Series 4", "pop4" },
					{ "Dragon Frontiers", "ex15" },
					{ "POP Series 5", "pop5" },
					{ "Power Keepers", "ex16" },
					{ "Diamond & Pearl", "dp1" },
					{ "DP Black Star Promos", "dpp" },
					{ "Mysterious Treasures", "dp2" },
					{ "POP Series 6", "pop6" },
					{ "Secret Wonders", "dp3" },
					{ "Great Encounters", "dp4" },
					{ "POP Series 7", "pop7" },
					{ "Majestic Dawn", "dp5" },
					{ "Legends Awakened", "dp6" },
					{ "POP Series 8", "pop8" },
					{ "Stormfront", "dp7" },
					{ "Platinum", "pl1" },
					{ "POP Series 9", "pop9" },
					{ "Rising Rivals", "pl2" },
					{ "Supreme Victors", "pl3" },
					{ "Arceus", "pl4" },
					{ "Pokémon Rumble", "ru1" },
					{ "HeartGold & SoulSilver", "hgss1" },
					{ "HGSS Black Star Promos", "hsp" },
					{ "HS—Unleashed", "hgss2" },
					{ "HS—Undaunted", "hgss3" },
					{ "HS—Triumphant", "hgss4" },
					{ "Call of Legends", "col1" },
					{ "BW Black Star Promos", "bwp" },
					{ "Black & White", "bw1" },
					{ "McDonald's Collection 2011", "mcd11" },
					{ "Emerging Powers", "bw2" },
					{ "Noble Victories", "bw3" },
					{ "Next Destinies", "bw4" },
					{ "Dark Explorers", "bw5" },
					{ "McDonald's Collection 2012", "mcd12" },
					{ "Dragons Exalted", "bw6" },
					{ "Dragon Vault", "dv1" },
					{ "Boundaries Crossed", "bw7" },
					{ "Plasma Storm", "bw8" },
					{ "Plasma Freeze", "bw9" },
					{ "Plasma Blast", "bw10" },
					{ "XY Black Star Promos", "xyp" },
					{ "Legendary Treasures", "bw11" },
					{ "Kalos Starter Set", "xy0" },
					{ "XY", "xy1" },
					{ "Flashfire", "xy2" },
					{ "Furious Fists", "xy3" },
					{ "Phantom Forces", "xy4" },
					{ "Primal Clash", "xy5" },
					{ "Double Crisis", "dc1" },
					{ "Roaring Skies", "xy6" },
					{ "Ancient Origins", "xy7" },
					{ "BREAKthrough", "xy8" },
					{ "BREAKpoint", "xy9" },
					{ "Generations", "g1" },
					{ "Fates Collide", "xy10" },
					{ "Steam Siege", "xy11" },
					{ "McDonald's Collection 2016", "mcd16" },
					{ "Evolutions", "xy12" },
					{ "Sun & Moon", "sm1" },
					{ "SM Black Star Promos", "smp" },
					{ "Guardians Rising", "sm2" },
					{ "Burning Shadows", "sm3" },
					{ "Shining Legends", "sm35" },
					{ "Crimson Invasion", "sm4" },
					{ "Ultra Prism", "sm5" },
					{ "Forbidden Light", "sm6" },
					{ "Celestial Storm", "sm7" },
					{ "Dragon Majesty", "sm75" },
					{ "Lost Thunder", "sm8" },
					{ "Team Up", "sm9" },
					{ "Detective Pikachu", "det1" },
					{ "Unbroken Bonds", "sm10" },
					{ "Unified Minds", "sm11" },
					{ "Hidden Fates", "sm115" },
					{ "Hidden Fates Shiny Vault", "sma" },
					{ "McDonald's Collection 2019", "mcd19" },
					{ "Cosmic Eclipse", "sm12" },
					{ "SWSH Black Star Promos", "swshp" },
					{ "Sword & Shield", "swsh1" },
					{ "Rebel Clash", "swsh2" },
					{ "Darkness Ablaze", "swsh3" },
					{ "Champion's Path", "swsh35" },
					{ "Vivid Voltage", "swsh4" },
					{ "Shining Fates", "swsh45" },
					{ "Shining Fates Shiny Vault", "swsh45sv" },
					{ "Battle Styles", "swsh5" },
					{ "Chilling Reign", "swsh6" },
					{ "Evolving Skies", "swsh7" },
					{ "Celebrations", "cel25" },
					{ "Celebrations: Classic Collection", "cel25c" },
					{ "Fusion Strike", "swsh8" },
					{ "Brilliant Stars", "swsh9" },
					{ "Brilliant Stars Trainer Gallery", "swsh9tg" },
					{ "Astral Radiance", "swsh10" },
					{ "Astral Radiance Trainer Gallery", "swsh10tg" },
					{ "Pokémon GO", "pgo" },
					{ "Lost Origin", "swsh11" },
					{ "Lost Origin Trainer Gallery", "swsh11tg" },
					{ "Silver Tempest", "swsh12" },
					{ "Silver Tempest Trainer Gallery", "swsh12tg" },
					{ "McDonald's Collection 2022", "mcd22" },
					{ "Crown Zenith", "swsh12pt5" },
					{ "Crown Zenith Galarian Gallery", "swsh12pt5gg" },
					{ "Scarlet & Violet", "sv1" },
					{ "Scarlet & Violet Black Star Promos", "svp" },
					{ "Paldea Evolved", "sv2" },
					{ "Scarlet & Violet Energies", "sve" },
					{ "Obsidian Flames", "sv3" },
					{ "151", "sv3pt5" },
					{ "Paradox Rift", "sv4" },
					{ "Paldean Fates", "sv4pt5" },
					{ "Temporal Forces", "sv5" },
					{ "Twilight Masquerade", "sv6" },
					{ "Shrouded Fable", "sv6pt5" },
					{ "Stellar Crown", "sv7" },
					{ "Surging Sparks", "sv8" },
					{ "Prismatic Evolutions", "sv8pt5" },
					{ "Journey Together", "sv9" },
					{ "Destined Rivals", "sv10" },
					{ "Black Bolt", "zsv10pt5" },
					{ "White Flare", "rsv10pt5" },
					{ "Mega Evolution", "me1" },
					{ "Phantasmal Flames", "me2" }
			};
		}
	}
}
